Update EditMemberGeneralView.vue
stamhoofd/stamhoofd pull request #32
Opened 2020-08-28 17:14 UTC by StijnCornelis

2020-09-05 19:03 UTC, SimonBackx commented on app/dashboard/src/views/dashboard/member/edit/EditMemberGeneralView.vue
> +                }))
Voor nieuwe leden mogen we niet automatisch 'toestemming voor groepsfoto's' aanzetten. Dan is er geen impliciete toestemming gegeven omdat het al aangevinkt was.

2020-09-05 19:05 UTC, SimonBackx commented on app/dashboard/src/views/dashboard/member/edit/EditMemberRecordsView.vue
> +    set allowOnlyGroupPictures(enabled: boolean) { this.setBooleanType(RecordType.OnlyGroupPictures, !enabled)}
Denk dat hier telkens het omgekeerde wordt teruggegeven en ingesteld. 
allowOnlyGroupPictures returnt true als OnlyGroupPictures afwezig is in de records

2020-09-05 19:05 UTC, SimonBackx commented on app/registration/src/views/registration/MemberGeneralView.vue
> +                }))
Zelfde als hierboven, mag hier gewoon weg

2020-09-05 19:05 UTC, SimonBackx commented on app/registration/src/views/registration/MemberGeneralView.vue
> +                }))
NoGroupPictures bestaat ook niet denk ik

2020-09-05 19:06 UTC, SimonBackx commented on app/registration/src/views/registration/MemberRecordsView.vue
> +
Tekstjes en variabelen lijken niet te kloppen

2020-09-05 19:08 UTC, SimonBackx commented on app/registration/src/views/registration/MemberRecordsView.vue
> +            this.memberDetails.records = this.memberDetails.records.filter(r => r.type == RecordType.NoData || r.type == RecordType.NoPictures||r.type == RecordType.OnlyGroupPictures || r.type == Rec
Denk dat `OnlyGroupPictures` ook weg mag, en dus wel weg gefilterd moet worden

2020-09-05 19:08 UTC, SimonBackx commented on app/registration/src/views/registration/MemberRecordsView.vue
> +    set allowOnlyGroupPictures(enabled: boolean) { this.setBooleanType(RecordType.OnlyGroupPictures, !enabled) }
Zelfde als hierboven ergens. Tis de inverse

2020-09-05 19:09 UTC, SimonBackx requested changes
Klopt nog niet helemaal. Zal zelf in de toekomst ook eens kijken of ik hiermee kan helpen, maar voorlopig werk ik nog even aan functies waar meer naar gevraagd werd

2020-09-06 17:10 UTC, StijnCornelis commented
Ik kan het niet laten om het los te laten, bij deze nog een poging! 
Let me know! Het filteren snap ik niet wat je bedoeld, al de rest wel!

2020-09-07 18:27 UTC, SimonBackx commented on app/dashboard/src/views/dashboard/member/edit/EditMemberRecordsView.vue
> +    get allowOnlyGroupPictures() { return !this.getBooleanType(RecordType.OnlyGroupPictures) }
Deze lijn is ook nog steeds de inverse ;)

2020-09-07 18:33 UTC, SimonBackx commented on app/registration/src/views/registration/MemberRecordsView.vue
> +            <Checkbox v-if="!allowGroupPictures" v-model="allowPictures" class="long-text">
Dit lijntje zou ik gewoon laten. Altijd vragen of er toestemming is voor foto's => als er geen toestemming is (zie lijnen hieronder, die zijn goed) dan toon je de extra vraag om wel toestemming te geven voor groepsfoto's

2020-09-07 18:34 UTC, SimonBackx commented on app/registration/src/views/registration/MemberRecordsView.vue
> +                {{ memberDetails.firstName }} mag tijdens de activiteiten worden gefotografeerd in groep voor publicatie op de website en sociale media van {{ organization.name }}.
Misschien hier wel wat meer beklemtonen dat het over groepsfoto's gaat

2020-09-07 18:35 UTC, SimonBackx commented on app/registration/src/views/registration/MemberRecordsView.vue
> +            this.memberDetails.OnlyGroupPictures =null
Mag gewoon weg ;)

2020-09-07 18:35 UTC, SimonBackx commented on app/registration/src/views/registration/MemberRecordsView.vue
> +    get allowOnlyGroupPictures() { return !this.getBooleanType(RecordType.OnlyGroupPictures) }
Hier nog inverse

2020-09-07 18:36 UTC, SimonBackx requested changes
Nog wat opmerkingen

2020-09-11 22:22 UTC, StijnCornelis commented
Ondertussen nog eens aangepast

2020-09-22 08:05 UTC, merged