Steekkaarten sorteren op prioriteit
stamhoofd/stamhoofd pull request #37
Opened 2020-09-08 21:24 UTC by tomvaneyck

Fixes #35 

Dit is *een* oplossing voor het probleem. Ik leg hier de nadruk op *een*, want er is eigenlijk niet echt een "mooie" manier om een enum van strings een natural ordering te geven. Ik ben wel van mening dat dit eerder de taak is van [stamhoofd/stamhoofd-structures](https://github.com/stamhoofd/stamhoofd-structures), aangezien er nog meer plaatsen kunnen zijn waar zo'n ordering nuttig is.

Puur praktisch: een andere oplossing zou zijn om een lijst met de volgorde te definiëren:
```typescript
const priorityOrder = [RecordTypePriority.High, RecordTypePriority.Medium, RecordTypePriority.Low;

sortedRecords() {
    return this.member.details.records.sort((record1, record2) => {
        const priority1: string = RecordTypeHelper.getPriority(record1.type);
        const priority2: string = RecordTypeHelper.getPriority(record2.type)

		return priorityOrder.indexOf(record1) - priorityOrder.indexOf(record2);
    })
}
```

Wat denken jullie hiervan?

Edit: nieuwe pull request is omdat mijn branches om zeep waren.

2020-09-10 12:46 UTC, SimonBackx commented
@tomvaneyck Bedankt voor de PR :) Dit is uiteraard iets dat er bij mag komen. Juist één opmerking: kan je de computed verhuizen naar een getter? Dat past iets meer bij de TypeScript achtige manier van Vue components schrijven.

Zoiets:
```
get sortedRecords() {
    // ...
}
```

2020-09-10 12:46 UTC, SimonBackx requested changes
Zie boven :)

2020-09-11 21:53 UTC, tomvaneyck commented
Ik heb het aangepast.

Het was het plan dat ik het ook ineens verplaatste naar stamhoofd/structures, maar ik heb dat niet kunnen testen want de sourcemaps worden nog niet goed gegenereerd. Nu is het op zijn minst toch aangepast en kan het later nog verplaatst worden.

2020-09-15 07:53 UTC, merged

2020-09-15 07:54 UTC, SimonBackx commented
Great work :)